<?php
/** Focused source-boundary regression for current documents and the employee drawer. */

$root = dirname( __DIR__ );
$repository = (string) file_get_contents( $root . '/includes/jotform/class-jotform-repository.php' );
$jotform_ui = (string) file_get_contents( $root . '/includes/jotform/class-jotform-ui.php' );
$drawer = (string) file_get_contents( $root . '/includes/class-ajax-handlers.php' );
$css = (string) file_get_contents( $root . '/assets/dashboard.css' );
$dashboard_js = (string) file_get_contents( $root . '/assets/dashboard.js' );
$fails = 0;
function current_documents_drawer_check( bool $condition, string $message ): void {
	global $fails;
	echo ( $condition ? 'PASS: ' : 'FAIL: ' ) . $message . "\n";
	$fails += $condition ? 0 : 1;
}

current_documents_drawer_check( 3 === substr_count( $repository, 'self::current_document_revision_scope( \'d\' )' ) && false !== strpos( $repository, 'GHCA_ACD_Jotform_Schema::training_table()' ) && false !== strpos( $repository, 'newer_revision.id>current_revision.id' ), 'shared training-ledger current-revision scope is used by recent, count and search queries' );
current_documents_drawer_check( false !== strpos( $jotform_ui, "self::document_error_page( 'The source revision changed") && false !== strpos( $jotform_ui, "self::document_error_page( 'The verified owner changed") && false !== strpos( $jotform_ui, 'int $status = 502' ) && false !== strpos( $jotform_ui, '409 === $status ? 409 : 502' ), 'stale source links return the audited, redacted HTTP 409 error page boundary' );
current_documents_drawer_check( false !== strpos( $drawer, 'role="tablist"' ) && false !== strpos( $drawer, 'role="tab"' ) && false !== strpos( $drawer, 'role="tabpanel"' ) && false !== strpos( $drawer, 'data-ghca-tablist' ) && false !== strpos( $drawer, 'GHCA_ACD_Roles::user_can_view_employee_documents()' ) && false !== strpos( $drawer, 'GHCA_ACD_Roles::user_can_view_communication_history()' ) && false !== strpos( $drawer, 'GHCA_ACD_Roles::user_can_edit_records()' ), 'drawer renders permission-aware ARIA tabs and panels' );
current_documents_drawer_check( false !== strpos( $drawer, 'data-ghca-reminder=' ) && false !== strpos( $drawer, 'data-ghca-pdf-packet=' ) && false !== strpos( $drawer, 'data-tracker="orientation"' ) && false !== strpos( $drawer, 'data-tracker="annual"' ) && false !== strpos( $drawer, 'data-ghca-edit-records=' ) && false !== strpos( $drawer, 'data-ghca-mark-reviewed=' ) && false !== strpos( $drawer, 'GHCA_ACD_Jotform_UI::render_recent_documents( $user_id )' ) && false !== strpos( $drawer, 'GHCA_ACD_Messaging_UI::render_history_section( $user_id )' ), 'drawer retains every existing action hook and reuses the document/history renderers' );
current_documents_drawer_check( false !== strpos( $drawer, 'Overall Compliance' ) && false !== strpos( $drawer, 'ghca-acd__drawer-compliance-ring' ) && false !== strpos( $drawer, 'Courses' ) && false !== strpos( $drawer, 'Certificate' ) && false !== strpos( $drawer, 'Next Due:' ) && false !== strpos( $drawer, 'Needs Attention' ) && 2 === substr_count( $drawer, '<details class="ghca-acd__drawer-disclosure">' ) && false === strpos( $drawer, '<details class="ghca-acd__drawer-disclosure" open>' ) && 2 <= substr_count( $drawer, 'ghca-acd__drawer-chevron' ), 'drawer includes the Clinical Precision summary, attention card, and compact attention/completed disclosures' );
current_documents_drawer_check( false !== strpos( $drawer, 'Compliance Report' ) && false !== strpos( $drawer, '<details class="ghca-acd__drawer-more">' ) && false === strpos( $drawer, 'aria-haspopup="menu"' ) && false === strpos( $drawer, 'role="menu"' ) && false === strpos( $drawer, 'role="menuitem"' ) && false === strpos( $drawer, 'View Certificates' ) && false === strpos( $drawer, 'Open Compliance Report' ) && false === strpos( $drawer, '>Resume<' ), 'primary actions use a native more disclosure without synthetic menu semantics, duplicate report buttons, or resume copy' );
current_documents_drawer_check( false !== strpos( $drawer, 'history_for_employee( $user_id, 1, 1 )' ) && false !== strpos( $drawer, 'GHCA_ACD_Messaging_Schema::tables_exist()' ) && false !== strpos( $drawer, "wp_date( 'M j, Y g:i a', \$created_ts )" ) && false !== strpos( $drawer, "'Last Reminder'" ), 'last-reminder metadata is queried only behind communication permission and schema readiness' );
current_documents_drawer_check( false !== strpos( $css, '1.7.0 Clinical Precision employee drawer' ) && false !== strpos( $css, 'width: min(850px, 100vw)' ) && false !== strpos( $css, 'var(--ghca-ui-brand)' ) && false !== strpos( $css, 'var(--ghca-ui-secondary)' ) && false !== strpos( $css, 'var(--ent-success' ) && false !== strpos( $css, 'var(--ent-warning' ) && false !== strpos( $css, 'var(--ent-danger' ), 'drawer uses the configured brand variables and semantic status variables' );
current_documents_drawer_check( false !== strpos( $css, '.ghca-acd__overlay--reminder' ) && false !== strpos( $css, '.ghca-acd__overlay--history' ) && false !== strpos( $css, '.ghca-acd__overlay--documents' ) && false !== strpos( $css, '@media (max-width: 680px)' ) && false !== strpos( $css, 'align-items: flex-end' ) && false !== strpos( $css, 'prefers-reduced-motion' ), 'connected popups have scoped responsive sheets, adaptive targets, and reduced-motion handling' );
current_documents_drawer_check( false !== strpos( $dashboard_js, 'var modalStack = []' ) && false !== strpos( $dashboard_js, 'stopImmediatePropagation' ) && false !== strpos( $dashboard_js, 'ghcaAcdOverlay.isTop' ) && false !== strpos( $dashboard_js, 'ArrowLeft' ) && false !== strpos( $dashboard_js, 'ArrowRight' ) && false !== strpos( $dashboard_js, 'e.key === \'Home\'' ) && false !== strpos( $dashboard_js, 'e.key === \'End\'' ) && false !== strpos( $dashboard_js, 'selectedTabs' ), 'drawer tabs and popup stack support keyboard navigation, topmost Escape, and session tab memory' );
current_documents_drawer_check( false !== strpos( $jotform_ui, 'Indexed Records' ) && false !== strpos( $jotform_ui, 'No employee documents found.' ) && false !== strpos( $drawer, 'Core employee records and employment status details.' ) && false !== strpos( $drawer, 'Employee Training Record' ) && false === strpos( $jotform_ui, 'Jotform Documents & External Training' ) && false === strpos( $drawer, 'Record Hash' ), 'drawer-facing document and administration copy is neutral and contains no invented record hash' );
current_documents_drawer_check( false !== strpos( $css, '1.6.5 employee drawer and connected popup presentation' ) && false === strpos( substr( $css, strpos( $css, '1.6.5 employee drawer and connected popup presentation' ) ), '#ghca-acd-announce-modal' ) && false === strpos( substr( $css, strpos( $css, '1.6.5 employee drawer and connected popup presentation' ) ), '.ghca-acd__announcement-' ), 'new visual rules use dedicated overlay scopes and do not target announcement selectors' );
current_documents_drawer_check( false !== strpos( $css, '.ghca-acd__drawer--employee .ghca-acd__drawer-more[open] > summary .ghca-acd__drawer-chevron' ) && false !== strpos( $css, '.ghca-acd__drawer--employee .ghca-acd__drawer-disclosure[open] > summary .ghca-acd__drawer-chevron' ) && false !== strpos( $css, 'padding-right: 14px' ) && false !== strpos( $css, 'padding: 12px 18px 12px 16px' ), 'drawer chevrons have scoped alignment, right padding, and open-state rotation' );
current_documents_drawer_check( false !== strpos( $css, '.ghca-acd__reminder-actions { position: sticky' ) && false !== strpos( $css, '.ghca-acd__history-filters { position: sticky' ), 'reminder actions and history filters remain visible while their popup bodies scroll' );
current_documents_drawer_check( false !== strpos( $repository, 'AS review_status' ) && false !== strpos( $jotform_ui, "'General document'" ) && false !== strpos( $jotform_ui, 'review_status_label' ) && false !== strpos( $jotform_ui, "'Awaiting review'" ), 'document search enriches each local row with an accurate external-training review status' );

/* -------------------------------------------------------------------------
 * Administration sub-page: Edit Records & Packet Generator (replaces the modal)
 * ---------------------------------------------------------------------- */
current_documents_drawer_check( false !== strpos( $drawer, 'data-ghca-admin-view="overview"' ) && false !== strpos( $drawer, 'data-ghca-admin-view="subpage"' ) && false !== strpos( $drawer, 'data-ghca-subpage-back' ), 'administration renders an overview view and an in-drawer sub-page with a back control' );
/* The modal shell must not come back: nothing opens it any more. */
current_documents_drawer_check( false === strpos( $drawer, "add_action( 'wp_footer', array( __CLASS__, 'render_edit_records_modal' ) );" ) && false !== strpos( $dashboard_js, 'function initEditRecordsSubpage' ) && false === strpos( $dashboard_js, 'function initEditRecordsModal' ), 'the edit-records overlay is retired in favour of the sub-page flow' );
/* Save path is unchanged: same endpoint, same nonce, same drawer reload. */
current_documents_drawer_check( false !== strpos( $dashboard_js, "params.append('action', 'ghca_acd_save_employee_records')" ) && false !== strpos( $dashboard_js, 'window.ghcaAcdReloadDrawer' ) && false !== strpos( $dashboard_js, "params.append('action', 'ghca_acd_get_edit_records_form')" ), 'the sub-page reuses the existing edit-records load and save endpoints' );
/* Milestones the audit calculator and packet depend on are editable here. */
current_documents_drawer_check( false !== strpos( $drawer, 'name="first_service_date"' ) && false !== strpos( $drawer, 'name="worked_alone_date"' ) && false !== strpos( $drawer, "'ghca_first_service_date'" ) && false !== strpos( $drawer, "'ghca_worked_alone_date'" ), 'first-service and worked-alone milestones are editable and persisted' );
/* ghca_audit_exclude belongs to the Audit Data tab; writing it here would clear it. */
current_documents_drawer_check( false === strpos( $drawer, "update_user_meta( $user_id, 'ghca_audit_exclude'" ), 'the sub-page never rewrites the audit exclude flag' );
/* Course records sit below the milestones section, per the approved layout. */
current_documents_drawer_check( strpos( $drawer, '2. Compliance Milestones' ) < strpos( $drawer, '3. Course Records' ) && false !== strpos( $drawer, 'name="registration_date"' ), 'course records follow the compliance milestones section' );
/* Packet pipeline is driven by the real job, not a decorative mock. */
current_documents_drawer_check( false !== strpos( $drawer, 'data-ghca-packet-mirror' ) && 3 === substr_count( $drawer, 'data-ghca-packet-step=' ) && false !== strpos( $dashboard_js, "mirror.querySelector('[data-ghca-packet-step=" ), 'the packet panel mirrors the live job progress in three real stages' );
/* No invented HRIS/ledger claims. */
current_documents_drawer_check( false === strpos( $drawer, 'Synchronized with HRIS' ) && false === strpos( $drawer, 'Immutable Ledger' ) && false === strpos( $drawer, 'Employee #%d' ), 'the sub-page makes no claims the plugin cannot back' );

exit( $fails ? 1 : 0 );
